### ISSUE TITLE
Help Needed: Large Extrinsic Calibration Error 

### ISSUE THREAD

**Issue by JH-Eric-Yang** [perfanalytics/pose2sim#146]
Hello! I'm facing challenges with performing extrinsic calibration using three 1080p webcams. The overall room layout is as illustrated below.
![image](https://github.com/user-attachments/assets/1c481439-e51c-479f-8de5-aea6a35b0d9f)

I have attempted to complete the extrinsic calibration with scene measurements. However, I consistently encounter very high residual calibration errors. I've tried various points and objects in the scene, but the errors remain large. In Blender, the cameras appear misaligned, all facing the y-axis when they should be oriented 
towards the x-axis based on the specified coordinate system.

`--> Residual (RMS) calibration errors for each camera are respectively [49.692, 97.073, 69.483] px,
which corresponds to [123.236, 265.555, 236.753] mm.`
![cordination](https://github.com/user-attachments/assets/18160ed4-2d03-4d84-9c57-d5976850b7b7)

![cam1_calibration](https://github.com/user-attachments/assets/06cc6e12-ba5f-418a-a4e2-f2f75590e4dd)
![cam2_calibration](https://github.com/user-attachments/assets/c150e390-5962-43c6-92df-426948de53ca)
![cam3_calibration](https://github.com/user-attachments/assets/7f8f220b-4af1-4459-9ed7-4745a8c65efd)

Could there be specific steps or configurations I might be missing that could lead to these calibration errors? Thank you!
[Calibration.zip](https://github.com/user-attachments/files/17683200/Calibration.zip)

**Comment by davidpagnon** [comment]
Hi, how did you do your intrinsic calibration?
I don't see any intrinsic calibration directory, and your intrinsic parameters (size, matrix, distortion) are the same in the example qualisys calibration and in the "Calib_scene.toml" file. Moreover, the size does not correspond to the resolution of your videos. 

- Make sure that you do not forget to do the intrinsic calibration
- You should also remove the Calib_qualisys.toml file, since it corresponds to the example sample rather than to your own cameras (you can also set overwrite_intrinsics to true in Config.toml)

**Comment by JH-Eric-Yang** [comment]
Thank you very much for your help! I completed the intrinsic calibration before moving on to the extrinsic calibration, but it didn't significantly affect the overall calibration results.

`--> Residual (RMS) calibration errors for each camera are respectively [69.823, 57.189, 52.271] px,
which corresponds to [179.844, 154.617, 169.104] mm.`

Below are the updated parameters after redoing both calibrations.
[calibration.zip](https://github.com/user-attachments/files/17689051/calibration.zip)

You can download the full calibration file [here](https://drive.google.com/file/d/1kUO8Yo5HxZ8K-PMwdx4UTVhJIbODqlR_/view?usp=drive_link).

All the webcams used are Elgato Facecam MK.2. I suspect there's something I've been overlooking that's influencing the results. Thank you again for your assistance!

**Comment by davidpagnon** [comment]
Hi, I've got the same results as you, which is not normal. 
I have several guesses:
- Are you sure you used the exact same configuration for the cameras between intrinsic and extrinsic parameters? You could have (1) configured them differently, (2) switched them, (3) taken photos instead of videos (oftentimes, especially with phones, even with the same parameters, the field of view of videos is cropped compared to when a photo is taken)
- Another guess: I use the[ solvePnP method from OpenCV](https://docs.opencv.org/3.4/d9/d0c/group__calib3d.html#ga357634492a94efe8858d0ce1509da869) to solve extrinsic parameters. It requires at least 6 points. You use 11 of them, but some of them are very close and it is almost equivalent to using 5 points. My suggestion would be for you to use only one point from the electric socket, but to add one or two others, for example there:
![image](https://github.com/user-attachments/assets/2f1393db-5237-41cc-80aa-a1f2f5b9f98c)

I'm curious to understand what is the issue there, but in case it does not work after trying that and you want to save some time, you can try a [Caliscope or FreeMocap calibration](https://github.com/perfanalytics/pose2sim?tab=readme-ov-file#convert-from-caliscope-anipose-freemocap-qualisys-optitrack-vicon-opencap-easymocap-or-biocv) and directly copy the calibration file within your Pose2Sim project.

**Comment by JH-Eric-Yang** [comment]
Hi, thank you very much for testing!

•	I'm sure the camera configurations are identical, and the calibration image is directly saved from the source frame, so each one originates from recorded videos.
•	I also conducted another extrinsic calibration using fewer points, focusing on those you highlighted. However, the results appear even more unusual, as shown below:

` --> Residual (RMS) calibration errors for each camera are respectively [238.952, 247.818, 53.347] px,
which corresponds to [573.775, 644.767, 171.488] mm.`
![new_calibration](https://github.com/user-attachments/assets/7abe03cd-436b-45b4-9205-4cbd8aad5999)

![cam1_calibration_new](https://github.com/user-attachments/assets/fa735716-4f03-47ee-b9c1-3b14df339ee3)

![cam2_calibration_new](https://github.com/user-attachments/assets/f7978e7d-5fb6-4618-8679-ef7b89769175)

![cam3_calibration_new](https://github.com/user-attachments/assets/34472992-34dd-4c1e-b0f4-355414aa1c4c)

You can find the calibration file [here](https://drive.google.com/file/d/19DV99rUkQWfb7DMpKfiasDHkkFKugWE0/view?usp=drive_link).

I’d really like to understand what might be causing this issue. I'm wondering if it could be related to the checkerboard used for calibration or possibly the method of recording. Specifically, the videos were captured using a script I wrote to simultaneously record from six webcams. Thank you very much.

**Comment by davidpagnon** [comment]
Hi all, sorry my job is keeping me quite busy, but I'll try to answer by the end of the week!
I face the same issue as you and I've never come across this, so I'll have to investigate.

**Comment by JH-Eric-Yang** [comment]
Hi, thank you so much for your help! I’ve been tied up with another task over the past few days, but I’ll follow your suggestion and get back to you tomorrow."

**Comment by davidpagnon** [comment]
Thanks for the update!
I'm glad you managed to get it work. However, I'm still surprised that calibration is still relatively bad... I would have expected a faulty intrinsic calibration, but if the checkerboard images are extracted from a video filmed with the same settings as the one for extrinsic parameters, I'm not sure.

**Comment by JH-Eric-Yang** [comment]
Hi, thank you so much for your reply. Apologies for the delay in responding. After using a new checkerboard for intrinsic calibration and using the board-based approach instead of the scene-based approach for extrinsic calibration, the results have significantly improved!
The new checkerboard I used for intrinsic calibration is as follows: 
![image](https://github.com/user-attachments/assets/a1c7ba63-ef1c-441f-a0c5-0e675fc43723)

 
The Intrinsic errors are 0.562, 0.491, 0.520
The Extrinsic calibration error is as follows:
![1](https://github.com/user-attachments/assets/aba09718-ac75-4f73-9703-ad8d1bb407cd)
![2](https://github.com/user-attachments/assets/59340944-a2ca-401f-b2ed-9088780c28c9)
![3](https://github.com/user-attachments/assets/5c763566-7560-4312-a0ef-52fec9963dc6)

`--> Residual (RMS) calibration errors for each camera are [2.563, 3.130, 2.182] px, corresponding to [6.188, 7.402, 5.425] mm.`

Although the intrinsic errors are still slightly above 0.50, I’m happy that it produced quite good kinematics estimation!
It seems that when depth information is not included, the extrinsic error appears to be lower (though I’m not sure if this observation is valid). I’m wondering if the way I set up the cameras (as below) might contribute to this.
 
![image](https://github.com/user-attachments/assets/63c0b3b1-abe6-4382-bc7b-1fb42f69824b)

Additionally, I’m considering whether it’s still necessary to further reduce the intrinsic error. Would doing so significantly improve the accuracy of the kinematic analysis?

Thank you again for you help!

**Comment by davidpagnon** [comment]
Hi, 

I'm glad it's working now! Now I still don't understand why the checkerboard approach works better than the scene measurements (not usually the case), but if you found a working solution, that's great :)
I think your intrinsic and extrinsic calibration look rather good, both from the pictures you attached and from the error values.

You are right that when depth information is not included, extrinsic error is usually lower. However, it can sometimes be delusional, since it means that results will only be as good in the plane of the checkerboard. Likewise, when you calibrate with 3D scene measurements but on a small volume, you will lose some accuracy in the 3D reconstruction when your subject steps out of the volume. 
I'm not too worried in your case but ultimately, you need to see if triangulation works okay and if your reprojection error is mostly below 2.5 cm.
