### ISSUE TITLE
Function using .toml file path accept the dictionary form of the .toml file ? 

### ISSUE THREAD

**Issue by ANaaim** [perfanalytics/pose2sim#34]
Hello, 

Thanks for the tool-box. Maybe I am not using it correctly, but in order to batch process some data (in some nasty for loop) I am modifying a toml file used in the different function

> 
```python
config_dict['project']['pose_folder_name'] = pose_folder_name
config_dict['project']['poseAssociated_folder_name'] = poseAssociated_folder_name
config_dict['project']['pose3d_folder_name'] = pose3d_folder_name

os.remove("temp.toml")
f = open("temp.toml", 'w')
toml.dump(config_dict, f)
f.close()
Pose2Sim.personAssociation("temp.toml")
Pose2Sim.triangulation("temp.toml")
Pose2Sim.filtering("temp.toml")
```
Would it be possible in the different function to be able to take a dictionary as a possible variable ? It would make that kind of thing easier. But I do not know if it is something that you would be interested in. 

```python
def calibration(config=os.path.join('User', 'Config.toml')):
    '''
    Cameras calibration from checkerboards or from qualisys files.
    '''

    from Pose2Sim.calibration import calibrate_cams_all
    
    if config is dict:
         config_dict = config
    else:
        config_dict = read_config_file(config)
    project_dir, seq_name, frames = base_params(config_dict)

```

Thanks

**Comment by davidpagnon** [comment]
Hi, 

You could do it slightly more concisely by replacing your code by:
```
with open('temp.toml', 'w') as f:
    toml.dump(config_dict, f)
```
No need to close and remove the file.

But you're right, it does not cost much to allow users to use the dictionary directly, instead of writing and opening the file!
I just added this option in the repository. 

Can you try and replace your `Pose2Sim.py` (find where it is with `pip show pose2sim`) with the last version [here](https://github.com/perfanalytics/pose2sim/blob/main/Pose2Sim/Pose2Sim.py)? If it works, then I will push you to the next release.

I'm also adding these lines of instruction in the Readme.md at https://github.com/perfanalytics/pose2sim#batch-processing:

**Comment by ANaaim** [comment]
Just tested it. Seems to work fine :). 

Thanks for the modification (and the advice on coding)
